name: Build   

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
          
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore -c Release
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      - name: Package
        run: dotnet pack --no-restore -c Release --output nupkg
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: object-url
          path: nupkg/
          retention-days: 1