name: Build   

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'examples/*'
      - 'readme.md'
jobs:
  build:
    uses: NMillard/ObjectUrl/.github/workflows/build-base-template.yml@main
    with:
      dotnet-version: '8.x'
      package-name: ObjectUrl